
AllCops:
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'tmp'

RSpec/EmptyExampleGroup:
  Enabled: false

Style/Documentation:
  Enabled: false

inherit_gem:
  rubocop-discourse: default.yml