name: Ruby On Rails CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PostgreSQL
      run: sudo apt-get -yqq install libpq-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Database
      working-directory: ${{env.api-dir}}
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: bin/rails db:create db:schema:load

    - name: Run ruboCop
      run: bundle exec rubocop

    - name: Build and test with rspec
      working-directory: ${{env.api-dir}}
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
      run: bundle exec rspec
